//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleSocialNetwork.Resources.Views.User {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Index_ru {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index_ru() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("SimpleSocialNetwork.Resources.Views.User.Index.ru", typeof(Index_ru).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string add_post {
            get {
                return ResourceManager.GetString("add_post", resourceCulture);
            }
        }
        
        internal static string admin {
            get {
                return ResourceManager.GetString("admin", resourceCulture);
            }
        }
        
        internal static string moderator {
            get {
                return ResourceManager.GetString("moderator", resourceCulture);
            }
        }
        
        internal static string send_message {
            get {
                return ResourceManager.GetString("send_message", resourceCulture);
            }
        }
        
        internal static string remove_friend {
            get {
                return ResourceManager.GetString("remove_friend", resourceCulture);
            }
        }
        
        internal static string follower_he {
            get {
                return ResourceManager.GetString("follower_he", resourceCulture);
            }
        }
        
        internal static string follower_she {
            get {
                return ResourceManager.GetString("follower_she", resourceCulture);
            }
        }
        
        internal static string add_friend {
            get {
                return ResourceManager.GetString("add_friend", resourceCulture);
            }
        }
        
        internal static string cancel_request {
            get {
                return ResourceManager.GetString("cancel_request", resourceCulture);
            }
        }
        
        internal static string edit_page {
            get {
                return ResourceManager.GetString("edit_page", resourceCulture);
            }
        }
        
        internal static string appoint_as_admin {
            get {
                return ResourceManager.GetString("appoint_as_admin", resourceCulture);
            }
        }
        
        internal static string appoint_as_moderator {
            get {
                return ResourceManager.GetString("appoint_as_moderator", resourceCulture);
            }
        }
        
        internal static string remove_moderator {
            get {
                return ResourceManager.GetString("remove_moderator", resourceCulture);
            }
        }
        
        internal static string block {
            get {
                return ResourceManager.GetString("block", resourceCulture);
            }
        }
        
        internal static string friends {
            get {
                return ResourceManager.GetString("friends", resourceCulture);
            }
        }
        
        internal static string new_post {
            get {
                return ResourceManager.GetString("new_post", resourceCulture);
            }
        }
        
        internal static string all_friends {
            get {
                return ResourceManager.GetString("all_friends", resourceCulture);
            }
        }
        
        internal static string your_friend {
            get {
                return ResourceManager.GetString("your_friend", resourceCulture);
            }
        }
        
        internal static string choose_photo {
            get {
                return ResourceManager.GetString("choose_photo", resourceCulture);
            }
        }
        
        internal static string request_send {
            get {
                return ResourceManager.GetString("request_send", resourceCulture);
            }
        }
    }
}
