//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleSocialNetwork.Resources.Views.User {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Information_ru {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Information_ru() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("SimpleSocialNetwork.Resources.Views.User.Information.ru", typeof(Information_ru).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string birthday {
            get {
                return ResourceManager.GetString("birthday", resourceCulture);
            }
        }
        
        internal static string country {
            get {
                return ResourceManager.GetString("country", resourceCulture);
            }
        }
        
        internal static string city {
            get {
                return ResourceManager.GetString("city", resourceCulture);
            }
        }
        
        internal static string university {
            get {
                return ResourceManager.GetString("university", resourceCulture);
            }
        }
        
        internal static string school {
            get {
                return ResourceManager.GetString("school", resourceCulture);
            }
        }
        
        internal static string job_place {
            get {
                return ResourceManager.GetString("job_place", resourceCulture);
            }
        }
        
        internal static string job_position {
            get {
                return ResourceManager.GetString("job_position", resourceCulture);
            }
        }
        
        internal static string phone_num {
            get {
                return ResourceManager.GetString("phone_num", resourceCulture);
            }
        }
        
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
    }
}
